#!/usr/bin/env python3
# TODO: review this file
"""Generate ``_project_index/api_map.{json,md}`` from the live SFI package.

The API map is an agent-consumable index of the public API surface. It
is regenerated by importing ``SFI`` and walking every first-level
subpackage listed in ``SFI.__all__``-equivalent introspection.

Usage
-----

   python scripts/gen_api_map.py             # overwrite map files
   python scripts/gen_api_map.py --check     # exit 1 if map is stale

Rules
-----

- A symbol is "public" iff its name does not start with ``_`` AND it is
  importable from the subpackage's top-level namespace.
- Classes and functions defined in ``SFI`` (by inspecting ``__module__``)
  are listed; re-exports from third-party packages (``jax``, ``numpy``)
  are filtered out.
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "_project_index"

SUBPACKAGES = [
    "SFI.statefunc",
    "SFI.inference",
    "SFI.trajectory",
    "SFI.langevin",
    "SFI.bases",
    "SFI.integrate",
    "SFI.diagnostics",
    "SFI.utils",
]


def _is_public_sfi_symbol(obj: Any, name: str) -> bool:
    if name.startswith("_"):
        return False
    mod = getattr(obj, "__module__", "") or ""
    return mod.startswith("SFI")


def _classify(obj: Any) -> str:
    if inspect.isclass(obj):
        return "class"
    if inspect.isfunction(obj) or inspect.isbuiltin(obj):
        return "function"
    if callable(obj):
        return "callable"
    return "object"


def _signature(obj: Any) -> str | None:
    try:
        sig = str(inspect.signature(obj))
    except (TypeError, ValueError):
        return None
    # Strip memory-address artefacts (e.g. ``<function array at 0x7f...>``)
    # that make the output nondeterministic across Python processes.
    import re

    return re.sub(r" at 0x[0-9a-fA-F]+", "", sig)


def _summary(obj: Any) -> str:
    doc = inspect.getdoc(obj) or ""
    first = doc.splitlines()[0].strip() if doc else ""
    return first


def inventory_module(mod_name: str) -> dict[str, Any]:
    mod = importlib.import_module(mod_name)
    entries: list[dict[str, Any]] = []
    for name in sorted(dir(mod)):
        obj = getattr(mod, name)
        if not _is_public_sfi_symbol(obj, name):
            continue
        entries.append(
            {
                "name": name,
                "kind": _classify(obj),
                "signature": _signature(obj),
                "summary": _summary(obj),
                "defined_in": getattr(obj, "__module__", None),
            }
        )
    return {
        "module": mod_name,
        "doc": _summary(mod),
        "symbols": entries,
    }


def build_map() -> dict[str, Any]:
    top = importlib.import_module("SFI")
    top_exports = [
        name
        for name in sorted(dir(top))
        if _is_public_sfi_symbol(getattr(top, name), name)
    ]
    return {
        "package": "SFI",
        "version": getattr(top, "__version__", "unknown"),
        "top_level_exports": top_exports,
        "subpackages": [inventory_module(m) for m in SUBPACKAGES],
    }


def render_markdown(data: dict[str, Any]) -> str:
    lines = [
        "# SFI API map",
        "",
        f"Package version: `{data['version']}`.",
        "",
        "> Auto-generated by `scripts/gen_api_map.py`. **Do not hand-edit.**",
        "",
        "## Top-level re-exports (`from SFI import …`)",
        "",
    ]
    for name in data["top_level_exports"]:
        lines.append(f"- `{name}`")
    lines.append("")
    for sp in data["subpackages"]:
        lines.append(f"## `{sp['module']}`")
        if sp["doc"]:
            lines.append("")
            lines.append(f"> {sp['doc']}")
        lines.append("")
        lines.append("| Name | Kind | Signature | Summary |")
        lines.append("| --- | --- | --- | --- |")
        for sym in sp["symbols"]:
            sig = sym["signature"] or ""
            sig = sig.replace("|", "\\|")
            summary = (sym["summary"] or "").replace("|", "\\|")
            lines.append(
                f"| `{sym['name']}` | {sym['kind']} | `{sig}` | {summary} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if on-disk map differs from introspection",
    )
    args = parser.parse_args()

    data = build_map()
    json_text = json.dumps(data, indent=2, sort_keys=False) + "\n"
    md_text = render_markdown(data)

    json_path = OUT_DIR / "api_map.json"
    md_path = OUT_DIR / "api_map.md"

    if args.check:
        stale = []
        if not json_path.exists() or json_path.read_text() != json_text:
            stale.append(str(json_path))
        if not md_path.exists() or md_path.read_text() != md_text:
            stale.append(str(md_path))
        if stale:
            print("Stale API map files:", file=sys.stderr)
            for p in stale:
                print(f"  {p}", file=sys.stderr)
            print("Run: python scripts/gen_api_map.py", file=sys.stderr)
            return 1
        print("API map is up to date.")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json_text)
    md_path.write_text(md_text)
    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
